# EDA - Brier Score

In [5]:
!uv pip install -r ../requirements.txt

Using Python 3.13.0 environment at: C:\Users\micha\projects\rmt\.venv
Resolved 15 packages in 295ms
Prepared 2 packages in 5.36s
Installed 4 packages in 2.19s
 + pandas==2.3.3
 + pytz==2025.2
 + seaborn==0.13.2
 + tzdata==2025.2

In [7]:
%reload_ext autoreload
%autoreload 2

In [8]:
import pandas as pd

In [30]:
df = pd.read_csv('../data/2024 football season/B1.csv'
                 , parse_dates=["Date"]
                 , dayfirst=True)

In [31]:
df.info(max_cols = 200)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 312 entries, 0 to 311
Data columns (total 121 columns):
 #    Column        Non-Null Count  Dtype
---   ------        --------------  -----
 0    Div           312 non-null    object
 1    Date          312 non-null    datetime64[ns]
 2    Time          312 non-null    object
 3    HomeTeam      312 non-null    object
 4    AwayTeam      312 non-null    object
 5    FTHG          312 non-null    int64
 6    FTAG          312 non-null    int64
 7    FTR           312 non-null    object
 8    HTHG          311 non-null    float64
 9    HTAG          311 non-null    float64
 10   HTR           311 non-null    object
 11   HS            311 non-null    float64
 12   AS            311 non-null    float64
 13   HST           311 non-null    float64
 14   AST           311 non-null    float64
 15   HF            311 non-null    float64
 16   AF            311 non-null    float64
 17   HC            311 non-null    float64
 18   AC            311 non-null    float64
 19   HY            311 non-null    float64
 20   AY            311 non-null    float64
 21   HR            311 non-null    float64
 22   AR            311 non-null    float64
 23   B365H         310 non-null    float64
 24   B365D         310 non-null    float64
 25   B365A         310 non-null    float64
 26   BWH           197 non-null    float64
 27   BWD           197 non-null    float64
 28   BWA           197 non-null    float64
 29   BFH           312 non-null    float64
 30   BFD           312 non-null    float64
 31   BFA           312 non-null    float64
 32   PSH           311 non-null    float64
 33   PSD           311 non-null    float64
 34   PSA           311 non-null    float64
 35   WHH           209 non-null    float64
 36   WHD           209 non-null    float64
 37   WHA           209 non-null    float64
 38   1XBH          304 non-null    float64
 39   1XBD          304 non-null    float64
 40   1XBA          304 non-null    float64
 41   MaxH          312 non-null    float64
 42   MaxD          312 non-null    float64
 43   MaxA          312 non-null    float64
 44   AvgH          312 non-null    float64
 45   AvgD          312 non-null    float64
 46   AvgA          312 non-null    float64
 47   BFEH          311 non-null    float64
 48   BFED          311 non-null    float64
 49   BFEA          311 non-null    float64
 50   B365>2.5      310 non-null    float64
 51   B365<2.5      310 non-null    float64
 52   P>2.5         311 non-null    float64
 53   P<2.5         311 non-null    float64
 54   Max>2.5       312 non-null    float64
 55   Max<2.5       312 non-null    float64
 56   Avg>2.5       312 non-null    float64
 57   Avg<2.5       312 non-null    float64
 58   BFE>2.5       287 non-null    float64
 59   BFE<2.5       287 non-null    float64
 60   AHh           312 non-null    float64
 61   B365AHH       308 non-null    float64
 62   B365AHA       308 non-null    float64
 63   PAHH          311 non-null    float64
 64   PAHA          311 non-null    float64
 65   MaxAHH        312 non-null    float64
 66   MaxAHA        312 non-null    float64
 67   AvgAHH        312 non-null    float64
 68   AvgAHA        312 non-null    float64
 69   BFEAHH        177 non-null    float64
 70   BFEAHA        177 non-null    float64
 71   B365CH        312 non-null    float64
 72   B365CD        312 non-null    float64
 73   B365CA        312 non-null    float64
 74   BWCH          198 non-null    float64
 75   BWCD          198 non-null    float64
 76   BWCA          198 non-null    float64
 77   BFCH          312 non-null    float64
 78   BFCD          312 non-null    float64
 79   BFCA          312 non-null    float64
 80   PSCH          312 non-null    float64
 81   PSCD          312 non-null    float64
 82   PSCA          312 non-null    float64
 83   WHCH          210 non-null    float64
 84   WHCD          210 non-null    float64
 85   WHCA          210 non-null    float64
 86   1XBCH         312 non-null    float64
 87   1XBCD         312 non-null    float64
 88   1XBCA         312 non-null    float64
 89   MaxCH         312 non-null    float64
 90   MaxCD         312 non-null    float64
 91   MaxCA         312 non-null    float64
 92   AvgCH         312 non-null    float64
 93   AvgCD         312 non-null    float64
 94   AvgCA         312 non-null    float64
 95   BFECH         312 non-null    float64
 96   BFECD         312 non-null    float64
 97   BFECA         312 non-null    float64
 98   B365C>2.5     312 non-null    float64
 99   B365C<2.5     312 non-null    float64
 100  PC>2.5        312 non-null    float64
 101  PC<2.5        312 non-null    float64
 102  MaxC>2.5      312 non-null    float64
 103  MaxC<2.5      312 non-null    float64
 104  AvgC>2.5      312 non-null    float64
 105  AvgC<2.5      312 non-null    float64
 106  BFEC>2.5      312 non-null    float64
 107  BFEC<2.5      312 non-null    float64
 108  AHCh          312 non-null    float64
 109  B365CAHH      312 non-null    float64
 110  B365CAHA      312 non-null    float64
 111  PCAHH         312 non-null    float64
 112  PCAHA         312 non-null    float64
 113  MaxCAHH       312 non-null    float64
 114  MaxCAHA       312 non-null    float64
 115  AvgCAHH       312 non-null    float64
 116  AvgCAHA       312 non-null    float64
 117  BFECAHH       312 non-null    float64
 118  BFECAHA       312 non-null    float64
 119  Unnamed: 119  0 non-null      float64
 120  Unnamed: 120  0 non-null      float64
dtypes: datetime64[ns](1), float64(112), int64(2), object(6)
memory usage: 295.1+ KB

In [32]:
df.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA,Unnamed: 119,Unnamed: 120
0,B1,2024-07-27,19:45,Anderlecht,St Truiden,1,0,H,0.0,0.0,...,2.08,1.81,2.12,1.87,2.02,1.81,2.08,1.89,NaN,NaN
1,B1,2024-07-27,17:15,Beerschot VA,Oud-Heverlee Leuven,0,0,D,0.0,0.0,...,1.94,1.94,2.00,1.99,1.90,1.90,2.00,1.99,NaN,NaN
2,B1,2024-07-28,17:30,Charleroi,Antwerp,0,1,A,0.0,1.0,...,2.08,1.82,2.12,1.83,2.04,1.78,2.08,1.91,NaN,NaN
3,B1,2024-07-26,19:45,Club Brugge,Mechelen,1,1,D,0.0,0.0,...,2.01,1.88,2.04,1.90,1.96,1.86,1.99,1.95,NaN,NaN
4,B1,2024-07-27,15:00,Dender,St. Gilloise,0,0,D,0.0,0.0,...,1.83,2.07,2.16,2.12,1.82,2.00,1.90,2.05,NaN,NaN

In [34]:
df_filter = df[['HomeTeam','AwayTeam', 'FTR', 'BFEH', 'BFED', 'BFEA']]

In [35]:
df_filter.count()

HomeTeam    312
AwayTeam    312
FTR         312
BFEH        311
BFED        311
BFEA        311
dtype: int64

In [42]:
df['FTR'].value_counts(normalize=True)

FTR
H    0.439103
D    0.288462
A    0.272436
Name: proportion, dtype: float64